# r-devel subpipeline
image: rocker/r-devel

stages:
  - build
  - check

build:
  stage: build
  tags:
    - docker
  script:
    - RD CMD build .
  artifacts:
    paths:
      - multicrispr_*.tar.gz
    name: "$CI_COMMIT_REF_NAME-dev-builds"

check:
  stage: check
  tags:
    - docker
  variables:
    http_proxy: http://www-proxy.t-online.de:80
#    R_ZIPCMD: /opt/conda/bin/zip
    _R_CHECK_FORCE_SUGGESTS_: 0
  script:
    - RD CMD check *tar.gz --as-cran --no-manual
  artifacts:
    expire_in: 1 week
    paths:
      - multicrispr.Rcheck/*

pages:
  script:
    - touch public
  artifacts:
    paths:
      - public
  only:
    - master